# THIS IS THE DEVELOPMENT DOCKER COMPOSE I’M USING
# DO NOT USE IT TO DEPLOY THE BOT

version: "3.8"

services:
  inhouse_bot:
    image: mrtolkien/inhouse_bot:beta
    build:
      context: .
    env_file: # Using in env file in dev to hide my bot key and such
      - .env
    volumes:
      - type: bind
        source: ./
        target: /inhouse_bot
      - type: volume
        source: dbsocket
        target: /var/run/postgresql
    depends_on:
      - db

  db:
    image: postgres:alpine

    environment:
      POSTGRES_DB: inhouse_bot
      POSTGRES_PASSWORD: pwd

    volumes:
      # Socket volume to communicate faster
      - type: volume
        source: dbsocket
        target: /var/run/postgresql

  adminer:
    image: adminer
    ports:
      - 8080:8080


volumes:
  dbsocket:
